---
- hosts: all
  become: true 
  tasks:

    - name: update repository index
      ansible.builtin.dnf:
        update_cache: yes
      
    - name: Install Apache2 Package
      ansible.builtin.dnf: 
        name: httpd
        state: latest

    - name: Install php Package
      ansible.builtin.dnf:
        name: php
        state: latest
