---
- hosts: all
  become: true 
  tasks:

    - name: update repository index
      ansible.builtin.package:
        update_cache: yes
      
    - name: Remove Apache2 Package
      ansible.builtin.dnf: 
        name: httpd
        state: absent

    - name: Remove php Package
      ansible.builtin.dnf:
        name: php
        state: absent
