---
- hosts: all
  become: true
  pre_tasks: 

    - name: Install Updates for CentOS
      ansible.builtin.dnf:
          update_only: yes
          update_cache: yes
          state: latest
      when: ansible_distribution == "CentOS"

    - name: Install updates for Ubuntu
      ansible.builtin.apt:
          upgrade: yes
          update_cache: yes
          state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

    - name: Install Apache webserver
      ansible.builtin.dnf:
          name: httpd
          state: latest
      when: ansible_distribution == "CentOS"

- hosts: db_server
  become: true
  tasks:

    - name: Install Database 
      ansible.builtin.apt:
          name: mariadb-server
          state: latest
      when: ansible_distribution == "Ubuntu"
