---
- hosts: all
  become: true
  pre_tasks: 

    - name: Install Updates for CentOS
      tags: Centos_update
      ansible.builtin.dnf:
          update_only: yes
          update_cache: yes
          state: latest
      when: ansible_distribution == "CentOS"

    - name: Install updates for Ubuntu
      tags: Ubuntu_update
      ansible.builtin.apt:
          upgrade: yes
          update_cache: yes
          state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: web_server
  become: true
  tasks:

    - name: Install Apache webserver
      tags: webserver
      ansible.builtin.dnf:
          name: 
            - httpd
            - php
          state: latest
      when: ansible_distribution == "CentOS"

    - name: Start Apache Service
      tags: webserver
      ansible.builtin.service:
         name: httpd
         state: started
      when: ansible_distribution == "CentOS"

    - name: Change the email in the configuration file 
      tags: webserver_change
      ansible.builtin.lineinfile:
         path: /etc/httpd/conf/httpd.conf
         regexp: '^ServerAdmin'
         line: ServerAdmin example@example.com
           # backup: yes
      when: ansible_distribution == "CentOS"
      register: httpd

    - name: restart httpd 
      tags: restart_httpd
      ansible.builtin.service:
         name: httpd
         state: restarted
      when: httpd.changed
        
    - name: Copy the file ansible server to centos server
      tags: webserver_copy
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644

    - name: Creating ansible user on workstations
      tags: defaults
      ansible.builtin.user:
        name: ansible
        group: root
        state: present

    - name: add sudoers file for ansible user
      tags: defaults
      ansible.builtin.copy:
        src: sudoer_ansible
        dest: /etc/sudoers.d/ansible
        owner: root
        group: root
        mode: 0440

    - name: adding ssh key for ansible user
      tags: defaults
      ansible.builtin.authorized_key:
        user: ansible
        key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCmtqvp69pkbo3e2ieFNtTFZ2S/4RrOIAG+hWBot+CQl9rxanb0qU1gyBTm9WPPvLdkvdj3iAt5F6QAMxd7j7+uG8ceUpa7KCkWMHJBl8s8zlXZQ17WApc4j1iBXsZmZ6XQJNmycsj8drYBLE1aY2k95N5vsJXgEh3m+dKAiOylFVhsQqkeYSgulT+m7+2to1IRPV7HEWbX5GI6EnwE6GkE7ag8pGM1UfSwzGvwL6uuruuY8/uWTYYxwpFdT5/zWs8yvleQmfIhYSkDy78JnN4wwO5rUxYhiTdZFaruPCJr9at83c84weezCTYdR8kbwq/DvvxF+uzwdWemPlg3qRsN+1Cu4qmKJUlSuTSTAPQ1fX5dMu4b+46pW2qDRPDEExlmCSkQAZC6ujn93yxrI5ts2adbOoj5j1pRc8C4HSlNu0jvB9n7Aid0u0afb/PU5p5ztKc1oS8mr8cJv+1Cm+E1qgWaEHLhNpmdhVWxtE+JojsNk8qNjvrKIMzT1zwXpc0= root@AnsibleServer"

- hosts: db_server
  become: true
  tasks:

    - name: Install Database
      tags: database 
      ansible.builtin.apt:
          name: mariadb-server
          state: latest
      when: ansible_distribution == "Ubuntu"
